version: '3.8'

services:
  app:
    image: laravelsail/php83-composer:latest
    container_name: laravel-app
    working_dir: /var/www/html
    command: php-fpm
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  web:
    image: nginx:alpine
    container_name: laravel-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
